name: Lychee

on:
  pull_request:
    branches:
      - main
      - release/*

jobs:
  lychee:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: lycheeverse/lychee-action@v1
        with:
          args: --include-fragments -p ./lychee-preprocess.sh documentation