# This workflow checks all links in the documentation using Lychee.

name: Lychee

on:
  pull_request:
    branches:
      - main
      - release/*

jobs:
  lychee:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository.
      - uses: actions/checkout@v4

      # Check documentation links with Lychee.
      - uses: lycheeverse/lychee-action@v2
        if: github.base_ref != 'release/5.0'
        with:
          args: --include-fragments -p ./lychee-preprocess.sh documentation
          