name: FAIL if UNRELEASED exists

on:
  pull_request:
    branches:
      - release/6.0
      - main
  push:
    branches: ["**"]
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Fail if UNRELEASED exists
        run: |
          if [ -f UNRELEASED ]; then
            echo "UNRELEASED file present — PR not allowed."
            exit 1
          fi

      - name: Continue
        run: echo "No UNRELEASED file found."
